### ISSUE TITLE
Add ODH dashboard

### ISSUE THREAD

**Issue by durandom** [operate-first/odh#12]
@HumairAK @tumido can we easily add https://github.com/opendatahub-io/odh-dashboard#open-data-hub-dashboard ?

It'll be included in the 0.9 release of ODH, but having it now would ease user interaction

**Comment by tumido** [comment]
yes, it should be easy to add it. On the other hand I'm unsure about the added value, since the dashboard is limited to the namespace where it's deployed - which goes against our intention to deploy each component into it's own namespace.

In other words, the dashboard can see only the components deployed in the very same namespace its deployed in.

**Comment by durandom** [comment]
@tumido that's a perfect shortcoming for an issue at upstream. https://github.com/opendatahub-io/odh-dashboard/issues/26

**Comment by tumido** [comment]
I actually wanted to learn a bit about the node.js on backend. So I took a shot at it myself. :slightly_smiling_face:

**Comment by tumido** [comment]
@durandom, would you like to have a dashboard deployed from upstream - showing only current namespace (useless on MOC and everywhere, since we don't have everything in a single namespace) or you'd rather see me deploying a forked version with the https://github.com/opendatahub-io/odh-dashboard/pull/27 applied, spanning all namespaces?

**Comment by durandom** [comment]
@tumido let's deploy the fork
